# Generated by Django 5.0.7 on 2024-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату производства товара:",
                null=True,
                verbose_name="Дата производства",
            ),
        ),
    ]
