# Generated by Django 5.0.7 on 2024-08-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="photo",
            new_name="image",
        ),
    ]
